workflows:
  ios-app:
    name: iOS App Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.example.aispeakingapp"  # Укажи свой Bundle ID
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS app
        script: |
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/**/*.ipa
    publishing:
      email:
        recipients:
          - "rasul131298@gmail.com"
